version: "3.7"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: bundle exec sidekiq -r ./app.rb
    networks:
      backend:
    depends_on:
      - redis

  redis:
    image: redis:5.0-alpine
    ports:
      - "6379:6379"
    networks:
      backend:

networks:
  backend:
